# Generated by Django 4.2.1 on 2023-06-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0067_bd_alter_user_emp_id_alter_user_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="Account_number",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="Bank_Name",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="IFSC_Code",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="emp_id",
            field=models.CharField(default="emp403", max_length=70),
        ),
    ]
