# Generated by Django 4.1.7 on 2023-06-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0068_user_account_number_user_bank_name_user_ifsc_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_type', models.CharField(choices=[('TB', 'Tea Break'), ('BB', 'Bio Break'), ('L', 'Lunch'), ('O', 'Other')], max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='BD',
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp130', max_length=70),
        ),
    ]
