# Generated by Django 4.1.7 on 2023-06-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0069_schedule_delete_bd_alter_user_emp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(choices=[('tea', 'TEA'), ('lunch', 'LUNCH'), ('bio', 'BIO'), ('other', 'OTHER')], default=False, max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp307', max_length=70),
        ),
    ]
