# Generated by Django 4.1.7 on 2023-06-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0073_alter_user_emp_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BD',
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp178', max_length=70),
        ),
    ]
