# Generated by Django 4.1.7 on 2023-06-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0074_delete_bd_alter_user_emp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='breack_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp591', max_length=70),
        ),
    ]
